name: Run tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run:
          sudo apt-get install cpanminus sqlite3
      - name: Install perl dependencies
        run: |
          sudo cpanm -n Config::Tiny Crypt::Eksblowfish::Bcrypt Crypt::Random Cwd Dancer2 Dancer2::Session::Cookie Data::Structure::Util DBD::SQLite DBI Digest::SHA Encode Getopt::Long HTML::Strip HTTP::Status Moo MooX::ClassAttribute namespace::clean Plack::Builder Plack::Middleware::TrailingSlashKiller Pod::Usage Scalar::Util Session::Storage::Secure strictures Template::Toolkit Time::Piece Try::Tiny
      - name: Install perl test dependencies
        run: |
          # Test::More and File::Spec are provided by perl-modules-*
          sudo cpanm -n Test::Warnings Test::Exception Test::Deep File::Temp File::Path Test::Perl::Critic Test::Pod Test::PerlTidy Plack::Test
      - name: Check out branch
        uses: actions/checkout@v2
      - name: Run lint tests
        env:
          TEST_AUTHOR: 1
        run:
          prove -wmlv t
      - name: Run integration tests
        run: prove -wmlrv t/integration
      - name: Run unit tests
        run: prove -wmlrv t/unit
